### PR TITLE
Fix links in PROPOSAL.md

### PR DESCRIPTION
**Pull request by andrenrwn**
The previous links were broken. This fixes the links in the markdown.

### CODE REVIEW

**Comment by emilygknight** [comment]
Looks good :)

**Comment by andrenrwn** [comment]
Adding a comment

**Review by emilygknight — APPROVED** [review]
Looks good

**Review by andrenrwn — COMMENTED** [review]
Approving myself, does it work?

**Review by acantu9 — COMMENTED** [review]
Looks good, thank you!

**Review by acantu9 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
